name: bonfire_app
description: Flutter app for browsing reddit.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  go_router: ^5.1.0
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
        - asset: assets/fonts/manrope/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/manrope/Manrope-ExtraBold.ttf
          weight: 900
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/roboto_mono/RobotoMono-Regular.ttf
        - asset: assets/fonts/roboto_mono/RobotoMono-Italic.ttf
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto_mono/RobotoMono-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/roboto_mono/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/roboto_mono/RobotoMono-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/roboto_mono/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto_mono/RobotoMono-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/roboto_mono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_mono/RobotoMono-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/roboto_mono/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/roboto_mono/RobotoMono-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/roboto_mono/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_mono/RobotoMono-BoldItalic.ttf
          style: italic
          weight: 700
